alixo1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog'))
]

blog/urls.py
from django.urls import path
from .views import home,registers,login_,logout_,contact,panel,addproduct,productslist,productslistuser,editproduct,deleteproduct
app_name = "Kazem"
urlpatterns = [
    path('',home,name="home"),
    path('register/', registers, name='register'),
    path('login/', login_, name='login'),
    path('logout/', logout_),
    path("contact/", contact, name="contact"),
    path("panel/", panel, name="panel"),
    path("addproduct/", addproduct, name="addproduct"),
    path("products/", productslist, name="productslist"),
    path("myproducts/", productslistuser, name="productslistuser"),
    path(r'editproduct/(?P<id>)', editproduct , name="editproduct"),
    path(r'deleteproduct/(?P<id>)', deleteproduct , name="deleteproduct"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.


class Products(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    quantity = models.IntegerField()
    price = models.IntegerField()
    def human_readable_title(self):
        return self.name.replace(' ', '_')
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Products
from django.forms import ModelForm
from . import models

class productform(ModelForm):
    class Meta:
        model = models.Products
        fields = ('name','quantity','price')

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User,Group
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail
from .models import Products
from django.db.models import Q
from django.urls import reverse


from django.shortcuts import render , get_object_or_404
from .forms import productform

# Create your views here.


def home(request):
    seller, created = Group.objects.get_or_create(name='seller')
    return render(request,"blog/home.html")

def registers(request):
    error_pass = False
    error_user = False
    if request.method == 'POST':
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password1")
        password_repeat = request.POST.get("password2")
        if password != password_repeat :
            error_pass = True
            return render(request, "blog/register.html", {"error_pass": error_pass})

        if User.objects.filter(username=username).exists() :
            error_user = True
            return render(request, "blog/register.html", {"error_user": error_user})

        user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email)
        user.set_password(password)
        user.save()

        return HttpResponseRedirect("/")
    return render(request, "blog/register.html")

def login_(request):
    error = False
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("/")
        elif user is None:
            error = True
    return render(request, "blog/login.html", {
        "error": error
    })

def logout_(request):
    logout(request)
    return HttpResponseRedirect("/")

def contact(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        text = request.POST.get("text")
        email = request.POST.get("email")
        send_mail(
                title,
                f"{text}  {email}",
                'ssckiau.es@gmail.com',
                ["webe21lopers@gmail.com"],
            )
        return render(request, "blog/contact-success.html")
    return render(request, "blog/contact.html")


def panel(request):
    seller, created = Group.objects.get_or_create(name='seller')
    kazem = False
    if request.method == 'POST':
        seller.user_set.add(request.user)
        return render(request, "blog/seller-done.html",{"kazem": kazem})
    if request.user.groups.filter(name = 'seller').exists():
        kazem = True
        print("++++++++++")
    else:
        kazem = False
        print("-------------")
    return render(request, "blog/panel.html",{"kazem": kazem})
    


def addproduct(request):
    seller, created = Group.objects.get_or_create(name='seller')
    kazem = False
    if request.user.groups.filter(name = 'seller').exists():
        kazem = True
        print(kazem)
    else:
        kazem = False
        print(kazem)
    if request.method == 'POST':
        name = request.POST.get("name")
        quantity = request.POST.get("quantity")
        price = request.POST.get("price")
        product = Products(name=name,quantity=quantity,price=price,author=request.user)
        product.save()
        return render(request, "blog/product-success.html")
    return render(request, "blog/addproduct.html",{"kazem": kazem})


    
def productslistuser(request):
    user_products = Products.objects.filter(author=request.user)
    return render(request, "blog/userproducts.html",{"user_products":user_products})

def productslist(request):
    productslist = Products.objects.all()
    if request.method == "POST":
        query = request.POST.get("title")
        search_list = Products.objects.filter(name__contains=query)
        return render(request, "blog/search.html", {"search_list": search_list })
    return render(request, "blog/products.html",{"productslist":productslist})


def editproduct(request , id=None):
    post = get_object_or_404(Products, id=id)

    editform = productform(request.POST or None , request.FILES or None, instance=post)
    if editform.is_valid():
        editform.save()
        return HttpResponseRedirect(reverse('blog:productslistuser'))
    context = {
        'form': editform,
    }
    return render(request, 'blog/editproduct.html',context)

def deleteproduct(request , id=None):
    post = get_object_or_404(Products, id=id)
    if post.delete():
        return HttpResponseRedirect(reverse('blog:productslistuser'))

blog/templates/blog/addproduct.html
{% extends 'blog/base.html' %}
    {% block title %}
اضافه کردن محصول
    {% endblock %}
{% block content %}
{% if kazem == True %}
<style>
        .container{
            max-width: 940px;
            }
    .form-control:focus{
        border-color: #2e3133;
        box-shadow: 1px 1px 1px  #2e3133 !important;
    }
    </style>
    <div class="container mb-5 mt-5">
        <div class="row mx-auto">
            <div class="col">
                <div class="card">
                    <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> ساخت محصول
                    </div>
                    <div class="card-body">
                        <form id="make_product" action="/addproduct/" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">نام محصول</label>
                                <input type="text" name="name" class="form-control" id="name" aria-describedby="nameproduct" placeholder="عنوان را وارد کنید" required>
                            </div>
                            <div class="form-group">
                                <label for="quantity">موجودی</label>
                                <input type="number" name="quantity" class="form-control" id="quantity" aria-describedby="quantity" placeholder="موجودی" required>
                            </div>
                            <div class="form-group">
                                <label for="price">قیمت</label>
                                <input type="number" name="price" class="form-control" id="price" aria-describedby="price" placeholder="قیمت محصول" required>
                            </div>
                            <div class="d-flex my-2">
                            <button type="submit" class="btn btn-outline-success text-center mx-auto" style="width: 150px;">ساخت محصول</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
شما فروشنده نیستید
{% endif %}


{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
<style>
.ax-bg-products{
border-radius: 15px;
background-color: #1E90FF;
margin:20px;
transition:0.3s ease;
}.ax-bg-products div{
    margin: 15px;
}.ax-bg-products a {
    margin: 20px;
    display: block;
    text-decoration: none;
    color: yellow;
}.ax-bg-products:hover{
-webkit-transform: translateY(-5px);
transform: translateY(-5px);
-webkit-box-shadow: 0 12px 17px rgba(0, 0, 0, 0.12);
box-shadow: 0 12px 17px rgba(0, 0, 0, 0.12);
}
</style>
    <div class="container-xl ax-inner my-xl-5">
        <div id="axapp" class="ax-inner-content">

            <!--  Navigation -->
            <div class="navbar navbar-expand-lg ax-nav row d-flex justify-content-space-around align-items-center py-4">
                <div class="col-6 mx-auto col-md-4 ax-nav-logo-section d-flex justify-content-start mr-4">
                    <div class="ax-nav-logo ax-icon-marketing" :class="{'ax-logo-fixed' : logo_fixed}"></div>
                </div>
                <div class="col-2 d-md-none d-flex mx-auto col-md-4 ax-nav-logo-section">
                    <div class="ax-nav-logo"></div>
                </div>
                <button @click="ax_fixed_logo()" class="col col-md-4 d-lg-none ax-menu-button btn collapsed"
                    type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="ax-icon-menu"></span>
                </button>
                <div class="col-lg d-lg-flex justify-content-end collapse navbar-collapse ax-mobile" id="navbar">
                    <ul class="navbar-nav ax-list-desktop">
                        <li class="nav-item"><a id="homepage" href="/"> صفحه اصلی</a></li>
                        <li class="nav-item"><a id="all_products" href="/products/">محصولات</a></li>
                        <li class="nav-item"><a id="contact_us" href="/contact/"> تماس با ما</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a id="panel" href="/panel/">پنل کاربری</a></li>
                        <li class="nav-item"><a id="logout" href="/logout/">خروج</a></li>
                        {% else %}

                        <li class="nav-item"><a id="login" href="/login/">ورود</a></li>
                        <li class="nav-item"><a id="register" href="/register/">ثبت نام</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>

            <!-- End Navigation -->



            {% block content %}

            {% endblock %}

            <div class="ax-foot-hr mw-100"></div>
            <footer class="w-100 h-100 row align-items-center">
                <div class="col-md-4 col-12 d-lg-block d-none mr-5 my-3">
                    <a href="#" class="btn ax-foot-design">وی کو چند</a>
                </div>
                <div class="ax-social col-md-4 col-12 d-flex justify-content-center align-items-center mx-lg-0 mx-auto" dir="rtl">
با قلبی خسته <p class="foot-ax-heart"> 💔 </p> مثل جغد بیداریم و کد میزنیم
                </div>
                <a href="#" class="col-12 ax-foot-mobile-btn d-lg-none d-flex justify-content-center my-3">وی کو چند</a>

            </footer>
        </div>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"
            integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD" crossorigin="anonymous">
        </script>
        <script src="https://unpkg.com/vue@3.0.3/dist/vue.global.prod.js"></script>
        <script src="assets/js/app.js"></script>
</body>

</html>

blog/templates/blog/contact-success.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="done">
    <div class="alert alert-success text-right text-center mx-auto mt-4 w-50" role="alert" dir="rtl">
  درخواست شما ثبت شد
<br>
                                <a href="/contact/" class="my-3 btn btn-outline-success text-center mx-auto" style="width: 150px;">ارسال پیام مجدد</a>

</div>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
    {% block title %}
فرم تماس با ما
    {% endblock %}
{% block content %}
<style>
        .container{
            max-width: 940px;
            }
    .form-control:focus{
        border-color: #2e3133;
        box-shadow: 1px 1px 1px  #2e3133 !important;
    }
    </style>
    <div class="container mb-5 mt-5">
        <div class="row mx-auto">
            <div class="col">
                <div class="card">
                    <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> تماس با ما
                    </div>
                    <div class="card-body">
                        <form id="contact_us_form" action="/contact/" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">موضوع</label>
                                <input type="text" name="title" class="form-control" id="title" aria-describedby="emailHelp" placeholder="عنوان را وارد کنید" required>
                            </div>
                            <div class="form-group">
                                <label for="email">ایمیل</label>
                                <input type="email" name="email" class="form-control" id="email" aria-describedby="email" placeholder="ایمیل شما" required>
                            </div>
                            <div class="form-group">
                                <label for="message">پیام</label>
                                <textarea class="form-control" id="message" name="text" rows="6" minlength="10" maxlength="250" placeholder="یک پیام بین حداقل ۱۰ و حداکثر ۲۵۰ کاراکتر وارد کنید" required></textarea>
                            </div>
                            <div class="d-flex my-2">
                            <button type="submit" class="btn btn-outline-success text-center mx-auto" style="width: 150px;">ارسال</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/editproduct.html
{% extends 'blog/base.html' %}
{% load i18n %}

{% block content %}
<br>
<br>
<br>
<div class="container mb-5 mt-5">
    <style>
        form {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            direction: ltr;
        }

        input {
            width: 300px;
            height: 50px;
            border-radius: 10px;
            margin: 20px;

        }

        label {
            width: 80px;
            color: black;
        }
    </style>
    <div class="row mx-auto">
        <div class="col">
            <div class="card">
                <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> ویرایش محصول
                </div>
                <div class="card-body">
                    <form method="post" id="edit_product" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary" type="submit">{% trans "ذخیره" %}</bottun>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
    {% block title %}
    فروشگاه وی کو چند - یک حرفه‌ای 
    {% endblock %}
{% block content %}
<div class="ax-hero row pb-5 pt-0 py-md-5 px-3 px-md-0">
    <div class="col-12 ax-hero-content text-center">
        <h2 class="h2">سلام. به فروشگاه آنلاین وبلوپرز خوش آمدید.</h2>
<style>
.heart{
animation: heartbeat 2s infinite;
}
@keyframes heartbeat
{
  0%
  {
    transform: scale( 1.75 );
  }
  20%
  {
    transform: scale( 1 );
  }
  40%
  {
    transform: scale( 1.75 );
  }
  60%
  {
    transform: scale( 1 );
  }
  80%
  {
    transform: scale( 1.75 );
  }
  100%
  {
    transform: scale( 1.75 );
  }
}
.heart-text{
    border: #1E90FF solid 2px;
    padding: 20px;
    border-radius:20px;
}
</style>
<br> <br>
<div class="heart-text">
        <h1 class="h1">وی کو چند</h1>
        <h2 class="h2">ما تلاشمون رو کردیم ، باگا زیاد بود</h2>
        <h2 class="h2">باگا هم که زیاد باشه، جاج خطا میگیره</h2>
        <h2 class="h2">جاج هم که خطا بگیره ما برنده نمیشیم :)))</h2>
        <h2 class="h2">ولی در کل دمتون گرم بابت مسابقه</h2><br>
        <h2 class="h2 heart" title="همش تقصیر جاج بود :)))">❤️</h2><br>
        <h2 class="h2">پرچم عرفانم بالاست</h2>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}
ورود در ویکو چند کبیر
{% endblock %}
{% block content %}
{% if error %}
<div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Oh Shit!!</strong> Your username or password is incorrect! {{error}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
{% endif %}
<form class="d-felx container w-50 justify-content-center validate-form" id="login_form" action="/login/" method="post">
    {% csrf_token %}
    <div class="wrap-input100 validate-input" data-validate="Username is required">
        <label class="my-2">نام کاربری</label>
        <input name="username" class="form-control" type="text" placeholder="یک نام کاربری وارد کنید">
    </div>

    <div class="wrap-input100 validate-input" data-validate="Password is required">
        <label class="my-2">رمز عبور</label>
        <input class="form-control" type="password" name="password" placeholder="رمز عبورتان را وارد کنید">
    </div>

    <div class="m-4 text-left">
        <button class="btn btn-primary" type="submit" name="submit">
            ورود
        </button>
    </div>
</form>
{% endblock %}

blog/templates/blog/panel.html
{% extends 'blog/base.html' %}
{% block title %}
پنل در ویکو چند کبیر
{% endblock %}
{% block content %}

<div class="d-felx container w-75 justify-content-center my-5">
{% if kazem == True %}

<div class="row bg-dark p-3 rounded">
<h3 class="h3 col-12 text-center py-3">پنل کاربری</h3>
<a id="make_new_product" class="btn bg-success text-white col-6 py-4" href="/addproduct/">
ورود به صفحه ساخت محصول</a>
<a class="btn bg-danger text-white col-6 py-4" id="my_products" href="/myproducts/">
ورود به صفحه محصولات</a>

</div>
  
{% endif %}

<style>
        .container{
            max-width: 940px;
            }
    .form-control:focus{
        border-color: #2e3133;
        box-shadow: 1px 1px 1px  #2e3133 !important;
    }
    </style>
    <div class="container mb-5 mt-5">
        <div class="row mx-auto">
            <div class="col">
                <div class="card">
                    <div class="card-header bg-secondary text-white text-center"><i class="fa fa-envelope"></i> ساخت محصول
                    </div>
                    <div class="card-body">
                        <form id="become_seller" action="/panel/" method="post">
                            {% csrf_token %}
                            <div class="d-flex my-2">
                            <button type="submit" class="btn btn-outline-success text-center mx-auto" style="width: 150px;"> فروشنده شوید </button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>


{% endblock %}

blog/templates/blog/product-success.html
{% extends "blog/base.html" %}
{% block content %}
    <div id="done">
    <div class="alert alert-success text-right text-center mx-auto mt-4 w-50" role="alert" dir="rtl">
  محصول ایجاد شد شما ثبت شد
<br>
                                <a id="make_new_product" href="/addproduct/" class="my-3 btn btn-outline-success text-center mx-auto" style="width: 150px;"> ساخت محصول جدید </a>

</div>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/products.html
{% extends 'blog/base.html' %}
{% block title %}
محصولات ما
{% endblock %}
{% block content %}
<style>
    .ax-text-products {
        font-size: 70px;
    }.rounded{
        border-radius:30px!important;
    }
</style>


<div class="d-felx container justify-content-center my-5">

    <div class="col-md-4 mx-auto mb-5">
        <form action="/products/" method="POST" id="search_products" dir="rtl" class="my-2">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="جست و جو در محصولات">
            </div>
            <div class="d-flex my-2">
                <button name="submit" type="submit" class="btn btn-success text-center mx-auto" style="width: 150px;">جست و
                    جو</button></div>
        </form>
    </div>

    <div class="row bg-dark p-3 rounded">
        <h3 class="h3 col-12 text-center py-3">محصولات</h3>
        <div class="row d-flex justify-content-center text-center" id="all_products">


            {% for productlist in productslist %}

            <div class="col-md-3 col-12 ax-bg-products {{ productlist.human_readable_title }}_{{ productlist.author.username }}">
                <div class="ax-text-products ax-icon-marketing"></div>
                <h4>نام محصول : {{ productlist.name }}</h4>
                <div>موجودی : {{ productlist.quantity }}</div>
                <div>قیمت : {{ productlist.price }}</div>
                <div>نام : {{ productlist.author.first_name }}</div>
                <div>نام خانوادگی : {{ productlist.author.last_name }}</div>


            </div>


            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
    {% block title %}
ثبت نام در ویکو چند کبیر
    {% endblock %}
{% block content %}

{% if error_pass %}
        <div class="container" id="errors">
            <div class="alert alert-danger alert-dismissible fade show text-right" role="alert" dir="rtl">
              گذرواژه و تکرار گذرواژه یکسان نیستند
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
    {% elif error_user %}
    <div class="container" id="errors">
            <div class="alert alert-danger alert-dismissible fade show text-right" role="alert" dir="rtl">
              نام کاربری شما در سیستم موجود است
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        </div>
     {% endif %}
	 
<form class="d-felx container w-50 justify-content-center validate-form" id="register_form" action="/register/" method="post">
                    {% csrf_token %}
					<div class="validate-input" data-validate="First Name is required">
						<label class="my-2">نام شما</label>
						<input name="first_name" class="form-control" type="text" placeholder="نام خود را وارد کنید">
					</div>

                    <div class="wrap-input100 validate-input" data-validate="Last Name is required">
						<label class="my-2">نام خانوادگی شما</label>
						<input name="last_name" class="form-control" type="text" placeholder="نام خانوادگی خود را وارد کنید">
					</div>

                    <div class="wrap-input100 validate-input" data-validate="Username is required">
						<label class="my-2">نام کاربری</label>
						<input name="username" class="form-control" type="text" placeholder="یک نام کاربری وارد کنید">
					</div>

                    <div class="wrap-input100 validate-input" data-validate="Email is required">
						<label class="my-2">ایمیل</label>
						<input name="email" class="form-control" type="email" placeholder="ایمیل شما">
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<label class="my-2">رمز عبور</label>
						<input class="form-control" type="password" name="password1" placeholder="رمز عبورتان را وارد کنید">
					</div>

                    <div class="wrap-input100 validate-input" data-validate = "Password repeat is required">
						<label class="my-2">تایید رمز عبور</label>
						<input class="form-control" type="password" name="password2" placeholder="رمز عبورتان را وارد کنید">
					</div>

					<div class="m-4 text-left">
						<button class="btn btn-primary" type="submit" name="submit">
							ثبت نام کنید
						</button>
					</div>
				</form>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% block title %}
محصولات ما
{% endblock %}
{% block content %}
<style>
    .ax-text-products {
        font-size: 70px;
    }
    .rounded{
        border-radius:30px!important;
    }
</style>



<div class="d-felx container justify-content-center my-5">

    <div class="col-md-4 mx-auto mb-5">
        <form action="/products/" method="POST" id="search_products" dir="rtl" class="my-2">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="جست و جو در محصولات">
            </div>
            <div class="d-flex my-2">
                <button name="submit" type="submit" class="btn btn-success text-center mx-auto" style="width: 150px;">جست و
                    جو</button></div>
        </form>
    </div>

    <div class="row bg-dark p-3 rounded">
        <h3 class="h3 col-12 text-center py-3">محصولات</h3>
        <div class="row d-flex justify-content-center text-center" id="all_products">





            {% for productlist in search_list %}

             <div class="col-md-3 col-12 ax-bg-products {{ productlist.human_readable_title }}_{{ productlist.author.username }}">
                <div class="ax-text-products ax-icon-marketing"></div>
                <h4>نام محصول : {{ productlist.name }}</h4>
                <div>موجودی : {{ productlist.quantity }}</div>
                <div>قیمت : {{ productlist.price }}</div>
                <div>نام : {{ productlist.author.first_name }}</div>
                <div>نام خانوادگی : {{ productlist.author.last_name }}</div>


            </div>


            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/seller-done.html
{% extends "blog/base.html" %}
{% block content %}

{% if kazem == True %}
    <div id="error">
    <div class="alert alert-success text-right text-center mx-auto mt-4 w-50" role="alert" dir="rtl">
شما فروشنده هستید
<br>

                                <a id="make_new_product" href="/addproduct/" class="my-3 btn btn-outline-success text-center mx-auto" style="width: 150px;"> ساخت محصول جدید </a>

<br>
</div>
    </div>
    {% else %}
<div id="done">
    <div class="alert alert-success text-right text-center mx-auto mt-4 w-50" role="alert" dir="rtl">
با موفقیت فروشنده شدید
<br>

                                <a id="make_new_product" href="/addproduct/" class="my-3 btn btn-outline-success text-center mx-auto" style="width: 150px;"> ساخت محصول جدید </a>

</div>
    </div>
    {% endif %}
{% endblock %}

blog/templates/blog/userproducts.html
{% extends 'blog/base.html' %}
{% block title %}
محصولات شما
{% endblock %}
{% block content %}
<style>
    .ax-text-products {
        font-size: 70px;
    }.rounded{
        border-radius:30px!important;
    }
</style>

<div class="d-felx container justify-content-center my-5">
    
    <div class="row bg-dark p-3 rounded">
        <h3 class="h3 col-12 text-center py-3">محصولات</h3>
        <div class="row d-flex justify-content-center text-center" id="all_products">



            {% for user_product in user_products %}

            <div class="col-md-3 col-12 ax-bg-products {{ user_product.name }}_{{ user_product.author.username }}">
                <div class="ax-text-products ax-icon-marketing"></div>
                <h4>نام محصول : {{ user_product.name }}</h4>
                <div>موجودی : {{ user_product.quantity }}</div>
                <div>قیمت : {{ user_product.price }}</div>
                <div>نام : {{ user_product.author.first_name }}</div>
                <div>نام خانوادگی : {{ user_product.author.last_name }}</div>


                <a id="edit_{{ user_product.name }}_{{ user_product.author.username }}" href="{% url 'blog:editproduct' id=user_product.id %}">ویرایش محصول</a>
              <a id="delete_{{ user_product.name }}_{{ user_product.author.username }}" href="{% url 'blog:deleteproduct' id=user_product.id %}">حذف محصول</a>

            </div>


            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}